name: Deploy to Website 🛫
on:
  workflow_dispatch:

jobs:
  deploy_website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to AWS
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${ { secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${ { secrets.HOST_DNS }}
          REMOTE_USER: ${ { secrets.USERNAME }}
          TARGET: ${ { secrets.TARGET_DIR }}

#      Access AWS
      - run: export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY }}
      - run: export AWS_SECRET_ACCESS_KEY=${{ secrets.SECRET_ACCESS_KEY }}
      - run: export AWS_DEFAULT_REGION=eu-west-1

#      ZIP folder as html.zip + push to s3
      - run: zip -r html.zip web
      - run: aws s3 cp html.zip s3://am-web-project/Web/html.zip

